version: 2.1

jobs:
  Push_To_Gitlab:
    docker:
      - image: node:latest
    steps:
      - checkout
      - run:
          name: Add Gitlab Remote URL
          command: git remote add gitlab ${GITLAB_REPO_URL}
      - run:
          name: Configure GitLab Credentials
          command: |
            git config --global credential.helper store
            git config --global user.email "${OWNER_EMAIL}"
            git config --global user.name "${OWNER_NAME}"
      - run:
          name: Push to Gitlab
          command: |
            git push gitlab

workflows:
  version: 2
  Publisher:
    jobs:
      - Push_To_Gitlab:
          name: Publish to Gitlab
          filters:
            branches:
              only: main